---
title: "Expansion Area"
author: "Ata"
format: html
editor: visual
---

```{r}
#| echo: false
#| message: false

library(terra)
library(here)
library(dplyr)
library(sf)
library(tmap)
library(cleangeo)
library(rgeos)
```

```{r}
rootdir <- getwd()
datadir <- ("~/capstone/data")
```

```{r}
#National Parks
national_parks <- st_read(here("R", "data", "Wildlife_Protection_Areas", "ASP_ROCC.shp")) |>
  st_make_valid()

#Political boundaries
department <- st_read(here("R", "data", "Political_Boundaries", "departamento.shp"))|>
  st_make_valid()

#Permited Land Use Boundaries

plu_boundaries <- st_read(here("R", "data", "Permited_Land_Use", "limite_put.shp"))|>
  st_make_valid()

```

```{r}
#Filter only the Departament that are in the Chaco Region
chaco_dpto <- filter(department, nom_dpto %in% c("ALTO PARAGUAY", "PDTE. HAYES", "BOQUERON"))

#Calculate area (hectares)
chaco_dpto <-dplyr::mutate(chaco_dpto, area = sf::st_area(chaco_dpto))|>
  mutate( area = as.numeric(area))|>
  mutate(area = area/10000)
  
#Print Map
tm_shape(chaco_dpto)+
  tm_borders()+
  tm_text("nom_dpto", size = 1/2)

```

```{r}
#Dissolve the Chaco Departament to get the interest area
chaco_region <- st_union(chaco_dpto, by_feature = FALSE, is_coverage = TRUE)|>st_make_valid()


#Convert sfc_POLYGON in to a SF
chaco_region <- st_sf(chaco_region)|>st_make_valid()

#Calculate area (hectares)
chaco_region <-dplyr::mutate(chaco_region, area = sf::st_area(chaco_region))|>
  mutate(area = as.numeric(area))|>
  mutate(area = area/10000)
  
#Print Map
tm_shape(chaco_region)+
  tm_borders()+
  tm_text("area", size = 1/2)

```




```{r}
#create the erase function
st_erase = function(x, y) st_difference(x, st_union(st_combine(y)))
```


```{r}
# Convert PLU boundaries to Spatial 
national_parks_sp <- as(national_parks, "Spatial")

# Clean the topology error
national_parks_clean <- clgeo_Clean(national_parks_sp)
report.clean <- clgeo_CollectionReport(national_parks_clean)
clgeo_SummaryReport(report.clean)

# plu_clean is a spatial object convert to sf
national_parks_clean_st <- st_as_sf(national_parks_clean, ) |>st_make_valid()
```



```{r}
# Convert PLU boundaries to Spatial 

national_parks_sp <- as(national_parks, "Spatial")

# Clean the topology error
national_parks_clean <- clgeo_Clean(national_parks_sp )
report.clean <- clgeo_CollectionReport(national_parks_clean)
clgeo_SummaryReport(report.clean)

# plu_clean is a spatial object convert to sf
plu_st <- st_as_sf(plu_clean, ) |>st_make_valid()

```

```{r}

# Convert PLU boundaries to Spatial 
plu_sp <- as(plu_boundaries, "Spatial")

# Clean the topology error
plu_clean <- clgeo_Clean(plu_sp)
report.clean <- clgeo_CollectionReport(plu_clean)
clgeo_SummaryReport(report.clean)

# plu_clean is a spatial object convert to sf
plu_st <- st_as_sf(plu_clean, ) |>st_make_valid()


#Dissolve the polygons so we have lest features in the future
plu_dissolve <- st_combine(plu_st)|>st_make_valid()

#Union of the PLU_dissolve and National Parks

plu_np <- st_union(plu_boundaries, national_parks, by_feature = FALSE, is_coverage = FALSE) |> st_make_valid()

plu_np_dissolve <- st_combine(plu_np)
#Convert sfc_POLYGON in to a SF
plu_np_sf <- st_sf(plu_np_dissolve)

#Calculate area (hectares)
plu_np_sf <-dplyr::mutate(plu_np_sf , area = sf::st_area(plu_np_sf ))|>
  mutate(area = as.numeric(area))|>
  mutate(area = area/10000)
  
#Print Map
tm_shape(plu_np_sf )+
  tm_fill("green") +
  tm_shape(chaco_region)+
  tm_borders()
```

```{r}
#create the erase function
st_erase = function(x, y) st_difference(x, st_union(st_combine(y)))

#create the Not Forest covert by erase the the Chaco Region with the Forest Covert
expansion_area <- st_erase(chaco_region, plu_np_sf)

tm_shape(expansion_area)+
  tm_fill(col = "red")
```

```{r}
#This chunk is generate some problems... can we check it

#transform  Forest Covert multi-polygon to polygon
fc_2000_chaco_pol <- st_cast(fc_2000_chaco, "POLYGON")|>
  mutate(class = "forest")
 

#transform Not Forest multi-polygon to polygon
nf_2000_chaco_pol <- st_cast(nf_2000_chaco, "POLYGON")|>
  mutate(class = "not forest")

#create the Land Use 
lu_2000 <- st_union(nf_2000_chaco_pol, fc_2000_chaco_pol, by_feature = TRUE, is_coverage = TRUE)

tm_shape(lu_2000)+
  tm_sf(col = class)

```

```{r}
st_erase(chaco_region, plu_np, precision = 30, do.subset = TRUE )
```

